site_name: UI5 Antares Pro
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono    
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: indigo
      accent: lime
  favicon: img/favicon.ico
  logo: img/logo.png

nav:
  - UI5 Antares Pro:
    - Introduction: index.md
    - License and Usage Notice: home/license_and_usage_notice.md
    - Installation: home/installation.md
    - Local Testing: home/local_testing.md
  - CreateEntry:
    - Overview: create_entry.md
    - Key Features: create_entry/key_features.md
    - Constructor: create_entry/constructor.md
  - UpdateEntry: update_entry.md
  - DeleteEntry: delete_entry.md
  - DisplayEntry: display_entry.md
  - Core Features:
    - Introduction: core_features.md
  - Change Log: change_log.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hasanciftci26
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hasan-%C3%A7ift%C3%A7i-4b3646170

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true        

repo_url: https://github.com/hasanciftci26/ui5-antares-pro
repo_name: ui5-antares-pro

extra_css:
  - stylesheets/extra.css

copyright: >
  &copy; 2025 <a href="https://github.com/hasanciftci26" target="_blank" rel="noopened">Hasan Ciftci</a>